service: upschool-admin-server
provider:
  name: aws
  runtime: nodejs20.x
  lambdaHashingVersion: '20201221'
  region: ap-south-1
  stage: ${opt:stage}
  environment:
    DB_PREFIX: ${self:provider.stage}_
    ACCESS_KEY_ID: ${file(config/${self:provider.stage}-config.yml):data.config.accessKeyId}
    SECRET_ACCESS_KEY: ${file(config/${self:provider.stage}-config.yml):data.config.secretAccessKey}
    REGION: ${self:provider.region}
    NODE_ENV: ${self:provider.stage}
    BUCKET_NAME: ${self:provider.stage}-upschool
    SECRET_KEY: ${file(config/${self:provider.stage}-config.yml):data.randomSecretKey.secretKey}    
    SEND_OTP_ARN: ${file(config/${self:provider.stage}-config.yml):data.sendOtpArn.arn}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:CreateTable
          Resource:
            - "*"
functions:
  upschool-admin-server-lambda:
    handler: handler.upschoolAdminServer
    events:
      - http:
          path: /v1/login
          method: POST
          cors: true
      - http:
          path: /v1/logout
          method: POST
          cors: true
      - http:
          path: /v1/addDigiCard
          method: POST
          cors: true
      - http:
          path: /v1/fetchIndividualDigiCard
          method: POST
          cors: true
      - http:
          path: /v1/editDigiCard
          method: POST
          cors: true
      - http:
          path: /v1/toggleDigiCardStatus
          method: POST
          cors: true
      - http:
          path: /v1/fetchDigiCardsBasedonStatus
          method: POST
          cors: true
      - http:
          path: /v1/addTopic
          method: POST
          cors: true
      - http:
          path: /v1/fetchIndividualTopic
          method: POST
          cors: true
      - http:
          path: /v1/fetchAllStudents
          method: POST
          cors: true
      - http:
          path: /v1/editTopic
          method: POST
          cors: true
      - http:
          path: /v1/toggleTopicStatus
          method: POST
          cors: true
      - http:
          path: /v1/fetchTopicsBasedonStatus
          method: POST
          cors: true
      - http:
          path: /v1/fetchPreLearningTopics
          method: POST
          cors: true
      - http:
          path: /v1/fetchPostLearningTopics
          method: POST
          cors: true
      - http:
          path: /v1/addChapter
          method: POST
          cors: true
      - http:
          path: /v1/fetchIndividualChapter
          method: POST
          cors: true
      - http:
          path: /v1/editChapter
          method: POST
          cors: true
      - http:
          path: /v1/toggleChapterStatus
          method: POST
          cors: true
      - http:
          path: /v1/fetchChaptersBasedonStatus
          method: POST
          cors: true
      - http:
          path: /v1/addUnit
          method: POST
          cors: true
      - http:
          path: /v1/fetchIndividualUnit
          method: POST
          cors: true
      - http:
          path: /v1/editUnit
          method: POST
          cors: true
      - http:
          path: /v1/toggleUnitStatus
          method: POST
          cors: true
      - http:
          path: /v1/fetchUnitsBasedonStatus
          method: POST
          cors: true
      - http:
          path: /v1/addClass
          method: POST
          cors: true
      - http:
          path: /v1/fetchIndividualStandard
          method: POST
          cors: true
      - http:
          path: /v1/editStandard
          method: POST
          cors: true
      - http:
          path: /v1/deleteStandard
          method: POST
          cors: true
      - http:
          path: /v1/fetchAllStandards
          method: POST
          cors: true
      - http:
          path: /v1/loginWithOTP
          method: POST
          cors: true
      - http:
          path: /v1/validateOTP
          method: POST
          cors: true      
      - http:
          path: /v1/insertSchool
          method: POST
          cors: true
      - http:
          path: /v1/fetchActiveSchool
          method: POST
          cors: true
      - http:
          path: /v1/toggleSchoolStatus
          method: POST
          cors: true
      - http:
          path: /v1/fetchIndividualSchool
          method: POST
          cors: true
      - http:
          path: /v1/updateSchool
          method: POST
          cors: true
      - http:
          path: /v1/getUserBulkuploadUrl
          method: POST
          cors: true
      - http:
          path: /v1/bulkUsersUpload
          method: POST
          cors: true
      - http:
          path: /v1/fetchSchoolIdNames
          method: POST
          cors: true
      - http:
          path: /v1/fetchAllUsersData
          method: POST
          cors: true
      - http:
          path: /v1/fetchUpschoolAndClientClasses
          method: POST
          cors: true
      - http:
          path: /v1/classSubscribe
          method: POST
          cors: true
      - http:
          path: /v1/fetchIndividualUserByRole
          method: POST
          cors: true
      - http:
          path: /v1/updateUsersByRole
          method: POST
          cors: true
      - http:
          path: /v1/toggleUserStatus
          method: POST
          cors: true
      - http:
          path: /v1/fetchClassBasedOnSchool
          method: POST
          cors: true
      - http:
          path: /v1/fetchInactiveUsersData
          method: POST
          cors: true
      - http:
          path: /v1/fetchArchivedSchool
          method: POST
          cors: true
      - http:
          path: /v1/fetchDigicardAndConcept
          method: POST
          cors: true
      - http:
          path: /v1/fetchAllConcepts
          method: POST
          cors: true
      - http:
          path: /v1/addConcepts
          method: POST
          cors: true
      - http:
          path: /v1/toggleConceptStatus
          method: POST
          cors: true
      - http:
          path: /v1/fetchIndividualConcept
          method: POST
          cors: true
      - http:
          path: /v1/updateConcept
          method: POST
          cors: true
      - http:
          path: /v1/addSubject
          method: POST
          cors: true
      - http:
          path: /v1/fetchAllSubjects
          method: POST
          cors: true
      - http:
          path: /v1/toggleSubjectStatus
          method: POST
          cors: true
      - http:
          path: /v1/fetchUnitAndSubject
          method: POST
          cors: true
      - http:
          path: /v1/fetchIndividualSubject
          method: POST
          cors: true
      - http:
          path: /v1/updateSubject
          method: POST
          cors: true
      - http:
          path: /v1/fetchSubjectIdName
          method: POST
          cors: true      
      - http:
          path: /v1/fetchClassesBasedonStatus
          method: POST
          cors: true  
      - http:
          path: /v1/fetchIndividualClass
          method: POST
          cors: true  
      - http:
          path: /v1/editClass
          method: POST
          cors: true 
      - http:
          path: /v1/toggleClassStatus
          method: POST
          cors: true 
      - http:
          path: /v1/addQuestions
          method: POST
          cors: true 
      - http:
          path: /v1/fetchAllQuestionsData
          method: POST
          cors: true 
      - http:
          path: /v1/fetchIndividualQuestionData
          method: POST
          cors: true
      - http:
          path: /v1/editQuestion
          method: POST
          cors: true
      - http:
          path: /v1/toggleQuestionStatus
          method: POST
          cors: true
      - http:
          path: /v1/addSection
          method: POST
          cors: true 
      - http:
          path: /v1/editSection
          method: POST
          cors: true 
      - http:
          path: /v1/fetchSchoolSection
          method: POST
          cors: true 
      - http:
          path: /v1/fetchSectionById
          method: POST
          cors: true 
      - http:
          path: /v1/fetchSectionByClientClassId
          method: POST
          cors: true
      - http:
          path: /v1/teacherSectionAllocation
          method: POST
          cors: true
      - http:
          path: /v1/fetchTeacherInfoDetails
          method: POST
          cors: true
      - http:
          path: /v1/fetchTeacherClassAndSection
          method: POST
          cors: true
      - http:
          path: /v1/fetchSubjectForClientClass
          method: POST
          cors: true
      - http:
          path: /v1/mappingSubjectToTeacher
          method: POST
          cors: true
      - http:
          path: /v1/fetchMappedSubjectForTeacher
          method: POST
          cors: true
      - http:
          path: /v1/fetchAllGroupsData
          method: POST
          cors: true
      - http:
          path: /v1/addGroups
          method: POST
          cors: true
      - http:
          path: /v1/toggleGroupStatus
          method: POST
          cors: true
      - http:
          path: /v1/fetchIndividualGroupData
          method: POST
          cors: true
      - http:
          path: /v1/editGroup
          method: POST
          cors: true
      - http:
          path: /v1/fetchAllTypesOfGroups
          method: POST
          cors: true
      - http:
          path: /v1/fetchDigicardIdAndName
          method: POST
          cors: true
      - http:
          path: /v1/setQuizConfiguration
          method: POST
          cors: true
      - http:
          path: /v1/addCMSUser
          method: POST
          cors: true    
      - http:
          path: /v1/editCMSUser
          method: POST
          cors: true
      - http:
          path: /v1/fetchIndividualCMSUser
          method: POST
          cors: true
      - http:
          path: /v1/fetchCMSUsersBasedonRoleStatus
          method: POST
          cors: true    
      - http:
          path: /v1/toggleCMSUserStatus
          method: POST
          cors: true
      - http:
          path: /v1/bulkToggleUsersStatus
          method: POST
          cors: true
      - http:
          path: /v1/bulkToggleDigiCardStatus
          method: POST
          cors: true
      - http:
          path: /v1/schoolubscriptionFeatures
          method: POST
          cors: true
      - http:
          path: /v1/teacherAccess
          method: POST
          cors: true
      - http:
          path: /v1/resetOrCreatePassword
          method: POST
          cors: true
      - http:
          path: /v1/bulkToggleTopicStatus
          method: POST
          cors: true
      - http:
          path: /v1/bulkToggleChapterStatus
          method: POST
          cors: true
      - http:
          path: /v1/bulkToggleUnitStatus
          method: POST
          cors: true
      - http:
          path: /v1/bulkToggleConceptStatus
          method: POST
          cors: true
      - http:
          path: /v1/bulkToggleSubjectStatus
          method: POST
          cors: true
      - http:
          path: /v1/bulkToggleClassStatus
          method: POST
          cors: true
      - http:
          path: /v1/bulkToggleCMSUserStatus
          method: POST
          cors: true
      - http:
          path: /v1/bulkToggleQuestionStatus
          method: POST
          cors: true
      - http:
          path: /v1/bulkToggleGroupsStatus
          method: POST
          cors: true
      - http:
          path: /v1/fetchAllQuestionCategories
          method: POST
          cors: true
      - http:
          path: /v1/fetchAllQuestionDisclaimers
          method: POST
          cors: true
      - http:
          path: /v1/addQuestionCategory
          method: POST
          cors: true
      - http:
          path: /v1/addQuestionDisclaimer
          method: POST
          cors: true
      - http:
          path: /v1/fetchIndividualCategory
          method: POST
          cors: true
      - http:
          path: /v1/fetchIndividualDisclaimer
          method: POST
          cors: true
      - http:
          path: /v1/updateQuestionCategory
          method: POST
          cors: true
      - http:
          path: /v1/updateQuestionDisclaimer
          method: POST
          cors: true
      - http:
          path: /v1/fetchQuestionMasters
          method: POST
          cors: true
      - http:
          path: /v1/toggleQuestionCategoryStatus
          method: POST
          cors: true
      - http:
          path: /v1/toggleQuestionDisclaimerStatus
          method: POST
          cors: true
      - http:
          path: /v1/bulkToggleQuestionCategoryStatus
          method: POST
          cors: true
      - http:
          path: /v1/bulkToggleQuestionDisclaimerStatus
          method: POST
          cors: true
      - http:
          path: /v1/fetchSourcesBasedonStatus
          method: POST
          cors: true
      - http:
          path: /v1/addQuestionSource
          method: POST
          cors: true
      - http:
          path: /v1/fetchIndividualSource
          method: POST
          cors: true
      - http:
          path: /v1/updateQuestionSource
          method: POST
          cors: true
      - http:
          path: /v1/toggleQuestionSourceStatus
          method: POST
          cors: true
      - http:
          path: /v1/bulkToggleQuestionSourceStatus
          method: POST
          cors: true
      - http:
          path: /v1/fetchSkillsBasedonStatus
          method: POST
          cors: true
      - http:
          path: /v1/addCognitiveSkill
          method: POST
          cors: true
      - http:
          path: /v1/fetchIndividualCognitiveSkill
          method: POST
          cors: true
      - http:
          path: /v1/updateCognitiveSkill
          method: POST
          cors: true
      - http:
          path: /v1/toggleCognitiveSkillStatus
          method: POST
          cors: true
      - http:
          path: /v1/bulkToggleCognitiveSkillStatus
          method: POST
          cors: true
      - http:
          path: /v1/addBluePrint
          method: POST
          cors: true 
      - http:
          path: /v1/fetchBluePrintsBasedonStatus
          method: POST
          cors: true 
      - http:
          path: /v1/toggleBluePrintStatus
          method: POST
          cors: true 
      - http:
          path: /v1/fetchIndividualBluePrint
          method: POST
          cors: true 
      - http:
          path: /v1/deleteDynamoDBData
          method: POST
          cors: true 
      - http:
          path: /v1/searchUsers
          method: POST
          cors: true 
      - http:
          path: /v1/usersPagination
          method: POST
          cors: true 
